# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  VoiceItAPIToken:
    Type: String
  VoiceItAPIKey:
    Type: String
  JWTKey:
    Type: String
  # Variables below should be blank in real deployments, but are used locally in dev
  DynamoHost:
    Type: String
    Default: ''

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref AccountsTable
        DYNAMO_HOST: !Ref DynamoHost
        VOICEIT_API_KEY: !Ref VoiceItAPIKey
        VOICEIT_API_TOKEN: !Ref VoiceItAPIToken
        JWT_KEY: !Ref JWTKey

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  RootWelcome:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/root
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi

  MenuWelcome:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/menu
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/menu
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi
  MenuFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.post
      CodeUri: ./dist/handlers/menu
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/menu
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi

  MobileMoneyMenuWelcome:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/mobilemoney
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/mobilemoney
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi

  MobileMoneyMenuFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.post
      CodeUri: ./dist/handlers/mobilemoney
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/mobilemoney
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi

  AccountInformationFuction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/mobilemoney/account-info
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/mobilemoney/account-info
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi

  PayABillWelcome:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/mobilemoney/pay-bill
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/mobilemoney/pay-bill
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi

  PayABillFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.post
      CodeUri: ./dist/handlers/mobilemoney/pay-bill
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/mobilemoney/pay-bill
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi

  ReturnWelcome:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/return
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/return
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi

  ReturnFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.post
      CodeUri: ./dist/handlers/return
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/return
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi

  TransferWelcome:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/mobilemoney/transfer
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/mobilemoney/transfer
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi

  TransferFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.post
      CodeUri: ./dist/handlers/mobilemoney/transfer
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/mobilemoney/transfer
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi

  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: project
          Value: bilt
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: LambdaAccessDynamo
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                Resource: !GetAtt AccountsTable.Arn
      PermissionsBoundary: arn:aws:iam::736485099071:policy/LambdaRoleBoundaries

Outputs:
  APIEndpoint:
    Description: 'API Endpoint'
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/dev/fr-FR'
