# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref AccountsTable

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  RootWelcome:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/root
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi

  CallerCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/callerCount
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/count
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi

  RecordMessageWelcome:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      CodeUri: ./dist/handlers/record
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/record
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi

  RecordMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.post
      CodeUri: ./dist/handlers/record
      Role: !GetAtt LambdaRole.Arn
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /{lang}/record
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi

  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies:
        - PolicyName: LambdaAccessDynamo
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                Resource: !GetAtt AccountsTable.Arn

Outputs:
  APIEndpoint:
    Description: 'API Endpoint'
    Value: !Sub 'https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/dev/fr-FR'
